version: '2.2'
 
services:
  db:
    image: 'postgres:10.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
 
  api:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
 
volumes:
  postgres:
