default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Apenas acrescentamos o nosso container como Host
  host: db
  # E colocamos o usuário default do postgreSQL
  user: postgres

development:
  <<: *default
  database: simba_development